use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

/// Maximum stride value to support
const MAX_STRIDE: usize = 8192;

fn main() {
    // Tell cargo to rerun if build.rs changes
    println!("cargo:rerun-if-changed=build.rs");

    // Generate stride implementations
    generate_stride_impls();
}

fn generate_stride_impls() {
    let out_dir = env::var_os("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir);

    // Create stride subdirectory in OUT_DIR
    let stride_dir = out_path.join("stride");
    fs::create_dir_all(&stride_dir).unwrap();

    // Define stride requirements for each type
    // (type_name, file_name, start, step)
    let stride_configs = vec![
        // 16-byte alignment types (multiple of element count to fill 16 bytes)
        ("f16", "f16", 8, 8),     // f16: 2 bytes × 8 = 16 bytes
        ("bf16", "bf16", 8, 8),   // bf16: 2 bytes × 8 = 16 bytes
        ("i16", "i16", 8, 8),     // i16: 2 bytes × 8 = 16 bytes
        ("u16", "u16", 8, 8),     // u16: 2 bytes × 8 = 16 bytes
        ("f32", "f32", 4, 4),     // f32: 4 bytes × 4 = 16 bytes
        ("i32", "i32", 4, 4),     // i32: 4 bytes × 4 = 16 bytes
        ("u32", "u32", 4, 4),     // u32: 4 bytes × 4 = 16 bytes
        ("f64", "f64", 2, 2),     // f64: 8 bytes × 2 = 16 bytes
        ("i64", "i64", 2, 2),     // i64: 8 bytes × 2 = 16 bytes
        ("u64", "u64", 2, 2),     // u64: 8 bytes × 2 = 16 bytes
        ("i8", "i8", 16, 16),     // i8: 1 byte × 16 = 16 bytes
        ("u8", "u8", 16, 16),     // u8: 1 byte × 16 = 16 bytes
        ("bool", "bool", 16, 16), // bool: 1 byte × 16 = 16 bytes
    ];

    for (type_name, file_name, start, step) in stride_configs {
        generate_type_strides(&stride_dir, type_name, file_name, start, step);
    }
}

fn generate_type_strides(
    out_dir: &Path,
    type_name: &str,
    file_name: &str,
    start: usize,
    step: usize,
) {
    let dest_path = out_dir.join(format!("{}_impls.rs", file_name));
    let mut file = fs::File::create(&dest_path).unwrap();

    // Write header
    writeln!(file, "// @generated").unwrap();
    writeln!(
        file,
        "// Auto-generated stride implementations for {}",
        type_name
    )
    .unwrap();
    writeln!(file, "// DO NOT EDIT THIS FILE MANUALLY").unwrap();
    writeln!(file).unwrap();
    writeln!(
        file,
        "// {} requires stride to be multiple of {} (up to {})",
        type_name, step, MAX_STRIDE
    )
    .unwrap();
    writeln!(file).unwrap();

    // Generate implementations
    // These files are included in modules that already have the necessary imports
    let mut stride = start;
    while stride <= MAX_STRIDE {
        writeln!(
            file,
            "impl ValidStride for StrideValidator<{}, {}> {{}}",
            type_name, stride
        )
        .unwrap();
        stride += step;
    }
}
